# Generated by Django 4.1.5 on 2023-01-26 22:17

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="amount_borrowed",
            field=djmoney.models.fields.MoneyField(
                decimal_places=4,
                max_digits=19,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(10000),
                    djmoney.models.validators.MaxMoneyValidator(100000),
                ],
            ),
        ),
    ]
