# Generated by Django 4.1.5 on 2023-01-26 17:36

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="amount_borrowed",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(10000),
                    djmoney.models.validators.MaxMoneyValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="loan_duration",
            field=models.IntegerField(help_text="Duration in days"),
        ),
    ]
