# Generated by Django 4.1.5 on 2023-01-26 22:28

import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_profile_amount_borrowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="amount_borrowed",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                max_digits=19,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(10000),
                    djmoney.models.validators.MaxMoneyValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="registered_company_number",
            field=models.CharField(
                help_text="Enter 8 digit number",
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="nomatch",
                        message="Please provide 8 digit number",
                        regex="\\d{8}",
                    )
                ],
            ),
        ),
    ]
